server:
  port: 8080

spring:
  application:
    name: user-management-service
  datasource:
    url: jdbc:postgresql://localhost:5433/user-management-db
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
  liquibase:
    change-log: classpath:db/changelog/db.changelog-master.yaml