server:
  port: 8080
  servlet:
    context-path: /api

spring:
  application:
    name: auth-service
  datasource:
    url: jdbc:postgresql://localhost:5433/user-management-db
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: validate
  liquibase:
    change-log: classpath:db/changelog/db.changelog-master.yaml
  sql:
    init:
      mode: always
      continue-on-error: true
  kafka:
    bootstrap-servers: localhost:9092
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer

jwt:
  secret-key: abc123def456ghi789jkl012mno345pqr
  expiration: 86400000 # 1 day
