server:
  port: 8080
  servlet:
    context-path: /api

spring:
  application:
    name: user-management-service
  datasource:
    url: jdbc:postgresql://localhost:5433/user-management-db
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: validate
  liquibase:
    change-log: classpath:db/changelog/db.changelog-master.yaml

jwt:
  secret-key: abc123def456ghi789jkl012mno345pqr
  expiration: 86400000 # 1 day