services:
  postgres:
    image: postgres:latest
    container_name: user_management_postgres
    environment:
      POSTGRES_DB: user-management-db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5433:5432"
    volumes:
      - .\volumes\postgres_data:/var/lib/postgresql/data

  kafka:
    image: bitnami/kafka:latest
    container_name: user_management_kafka
    ports:
      - "9092:9092"
    environment:
      - KAFKA_CFG_PROCESS_ROLES=broker,controller  # Указываем роли
      - KAFKA_CFG_NODE_ID=1
      - KAFKA_KRAFT_CLUSTER_ID=r4zt_wrqTRuT7W2NJsB_GA # Любая уникальная строка

      # Настройки listeners
      - KAFKA_CFG_LISTENERS=PLAINTEXT://:9092,CONTROLLER://:9093
      - KAFKA_CFG_ADVERTISED_LISTENERS=PLAINTEXT://localhost:9092
      - KAFKA_CFG_CONTROLLER_QUORUM_VOTERS=1@kafka:9093
      - KAFKA_CFG_CONTROLLER_LISTENER_NAMES=CONTROLLER
      - KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP=CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT
    volumes:
      - .\volumes\kafka_data:/bitnami/kafka

  mailhog:
    image: mailhog/mailhog:latest
    container_name: user_management_mailhog
    ports:
      - "1025:1025"  # SMTP-порт для отправки писем
      - "8025:8025"  # Веб-интерфейс (http://localhost:8025)
    restart: always

volumes:
  postgres_data:
  kafka_data: